name: songon_on
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  mongo_dart: ^0.9.2
  get: 4.6.6
#  realm: ^1.5.0
  velocity_x: ^4.1.1
  line_icons: ^2.0.3
  iconsax: ^0.0.8
  pocketbase: ^0.15.1
#  get_storage: ^2.0.3
  flutter: 
    sdk: flutter
#  image_picker: ^1.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

