class AppModels {

  Map<dynamic, String> CategorieService = {
    '1': 'Restaurant',
    '2': 'Hôtel',
    '3': 'Café',
    '4': 'Bar',
    '5': 'Fast Food',
    '6': 'Boulangerie',
    '7': 'Pâtisserie',
    '8': 'Boucherie',
    '9': 'Charcuterie',
    '10': 'Traiteur',
    '11': 'Épicerie',
    '12': 'Supermarché',
    '13': 'Bureau de tabac',
    '14': 'Presse',
    '15': 'Librairie',
    '16': 'Fleuriste',
    '17': 'Pharmacie',
    '18': 'Parfumerie',
    '19': 'Bijouterie',
    '20': 'Horlogerie',
    '21': 'Opticien',
    '22': 'Vêtements',
    '23': 'Chaussures',
    '24': 'Maroquinerie',
    '25': 'Lingerie',
    '26': 'Mercerie',
    '27': 'climatiseur',
    '28': 'Électroménager',
    '29': 'Informatique',
    '30': 'Plombier',
  };

}